# Generated by Django 4.0.2 on 2022-02-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_remove_avaliacoes_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respostas',
            old_name='resposta',
            new_name='correta',
        ),
    ]
