# Generated by Django 4.0.2 on 2022-02-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacoes',
            name='autor',
        ),
    ]
